version: '3.8' # Trengs ikke, kan slettes.


services:
  db:
    image: mariadb:latest
    container_name: mariadb_soketeig
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: soketeig_db
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - soketeig_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_soketeig
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"

volumes:
  soketeig_data: